In [9]:
!pip install tensorflow


Access is denied.


In [10]:
!pip install --user tensorflow


Access is denied.


In [1]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
!python --version





Python 3.13.5


In [6]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.
import tensorflow as tf

scalar = tf.constant(10)

print("Value:", scalar.numpy())
print("Shape:", scalar.shape)
print("Data type:", scalar.dtype)


Value: 10
Shape: ()
Data type: <dtype: 'int32'>


In [7]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.
vector = tf.constant([2,4,6,8]) 
print(f"Vector shape: {vector.shape}, values: {vector.numpy()}")

Vector shape: (4,), values: [2 4 6 8]


In [9]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.
import tensorflow as tf

matrix = tf.constant([[1, 2], [3, 4]])

print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)


Matrix shape: (2, 2)
Matrix dtype: <dtype: 'int32'>


In [10]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.
import tensorflow as tf

# Create tf.Variable
a = tf.Variable(5.0)

# Print current value
print("Current value:", a.numpy())


Current value: 5.0


In [11]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.
import tensorflow as tf

# Create tf.Variable
a = tf.Variable(5.0)

# Update value
a.assign(10.0)

# Print updated value
print("Updated value:", a.numpy())

Updated value: 10.0


In [12]:
# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.
a=tf.Variable([[1.0, 2.0], [3.0, 4.0]])
a.assign_add([[1.0, 1.0], [1.0, 1.0]])
print(a.numpy())


[[2. 3.]
 [4. 5.]]


In [13]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().

import tensorflow as tf

# Create constant tensors
a = tf.constant([[1, 2],
                 [3, 4]])

b = tf.constant([[5, 6],
                 [7, 8]])

# Matrix multiplication
c = tf.matmul(a, b)

# Print result
print(c.numpy())


[[19 22]
 [43 50]]


In [14]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.
import tensorflow as tf

# Create random tensor
random_tensor = tf.random.uniform(shape=(3, 3))

# Print shape, dtype, and values
print("Shape:", random_tensor.shape)
print("Dtype:", random_tensor.dtype)
print("Values:\n", random_tensor.numpy())


Shape: (3, 3)
Dtype: <dtype: 'float32'>
Values:
 [[0.7598965  0.943468   0.9917395 ]
 [0.7300943  0.03416908 0.54371154]
 [0.643379   0.1527915  0.9979503 ]]
